-- Generated by nwg-displays on 2026-07-27 at 07:07:12. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@144.15",
    position = "297x1440",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@120.0",
    position = "0x0",
    scale = 1.0
})
